# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
 branches:
   include:
     - master

pool:
 vmImage: 'windows-latest'

variables:
 buildPlatform: 'Any CPU'
 buildConfiguration: 'Release'
 solution: '**/DoughManager.sln'
 project: '**/DoughManager.Api.csproj'

steps:

- task: NuGetToolInstaller@1
  name: 'NugetToolInstaller'
  displayName: 'Nugget Tool Installer Downloading'

- task: NuGetCommand@2
  name: 'NugetPackageRestore'
  displayName: 'Restoring Nuget Packages'
  inputs:
    command: 'restore'
    restoreSolution: '$(solution)'
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  name: 'Publish'
  displayName: 'Publish'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '$(project)'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  name: 'PublishBuildArtifactsToPipeline'
  displayName: 'Publish Build Artifacts To Pipeline'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'DoughManager'
    publishLocation: 'Container'
    zipAfterPublish: false




