version: "3.9"

services:
  myapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: myapi_dough_manager
    command: ["dotnet", "watch", "run", "--urls", "http://0.0.0.0:8000"]
    volumes:
      - ./:/app
      - /app/bin
      - /app/obj
    ports:
      - "8000:8000"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
    depends_on:
      - sqlserver
    networks:
      - backend-network

  sqlserver:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: sqlserver_dough_manager
    platform: linux/amd64
    environment:
      SA_PASSWORD: "Gandari12"
      ACCEPT_EULA: "Y"
    ports:
      - "14330:1433"
    networks:
      - backend-network

networks:
  backend-network: